#!/bin/bash
ln -s ${OPENSHIFT_DATA_DIR}uploads ${OPENSHIFT_REPO_DIR}/php/webroot/uploads
echo "Files sym links created"
chmod +x "$OPENSHIFT_REPO_DIR/php/bin/cake"

echo "Starting Proxy"
cd $OPENSHIFT_REPO_DIR/MySQLProxy/run
java -jar MySQLProxy.jar &
echo "Running Proxy"